import Link from "next/link";
import { Button } from "@/components/Button";
import { Container } from "@/components/Container";
import { createPageMetadata } from "@/lib/metadata";

export const metadata = createPageMetadata({ title: "Documentation", description: "The AICA engineering record: programme documentation, evidence status, development structure, and technical progress.", path: "/documentation" });

const nav = [["Overview", "#overview"], ["Library", "#library"], ["Document Structure", "#structure"], ["Evidence Status", "#evidence"], ["Principles", "#principles"], ["Programme History", "#history"], ["Records", "#records"]] as const;
const library = [
  ["Programme overview", "Programme Overview", "Mission, programme structure, engineering philosophy, and development approach.", "/documentation/program-overview", ""],
  ["Research", "Research Programme", "Research areas, current engineering questions, methodology, and validation strategy.", "/research", ""],
  ["System architecture", "System Architecture", "High-level relationship between propulsion, energy, control, safety, structures, and software.", "", "Available within programme documentation"],
  ["Development roadmap", "Development Roadmap", "Programme phases from long-term concept research through simulation, subsystem development, integration, demonstrator development, and future validation.", "/roadmap", ""],
  ["Engineering journal", "Engineering Journal", "Design notes, programme updates, technical observations, and development milestones.", "/journal", ""],
  ["Technical notes", "Technical Notes", "Focused engineering records covering specific assumptions, methods, analyses, and design decisions.", "", "In development"],
] as const;
const documentClasses = [
  { n: "01", title: "Concept documents", purpose: "Capture ideas, assumptions, candidate architectures, and early engineering reasoning.", status: "Exploratory · Subject to change", examples: ["concept studies", "architecture sketches", "feasibility notes", "research questions"] },
  { n: "02", title: "Analysis documents", purpose: "Record analytical work, simulation methods, modelling assumptions, and comparative engineering studies.", status: "Model-supported · Not yet physical validation", examples: ["CFD studies", "FEA studies", "energy models", "control simulation", "trade studies"] },
  { n: "03", title: "Validation documents", purpose: "Record results from physical subsystem testing and experimental engineering work.", status: "Experiment-supported", examples: ["bench tests", "component validation", "thermal tests", "structural tests", "hardware-in-the-loop results"], future: true },
  { n: "04", title: "Vehicle test documents", purpose: "Record integrated prototype and future vehicle testing.", status: "Measured vehicle evidence", examples: ["ground tests", "integrated system tests", "flight-test reports", "measured vehicle performance"], future: true },
];
const evidence = [["Concept", "Early engineering hypothesis or architecture direction."], ["Simulated", "Supported by analytical or numerical modelling."], ["Bench validated", "Supported by physical subsystem or component testing."], ["Prototype validated", "Supported by integrated prototype testing."], ["Measured", "Observed directly during representative physical testing."]] as const;
const principles = [["Traceability", "Important assumptions and design decisions should have a documented engineering basis."], ["Versioning", "Engineering understanding evolves. Documents should reflect meaningful revisions rather than silently rewriting programme history."], ["Limitations", "Known uncertainties, assumptions, model limitations, and validation gaps should be stated where relevant."], ["Evidence before claims", "Published performance statements should reflect the maturity of the evidence supporting them."]] as const;
const records = ["Concept Evolution", "Engineering Architecture", "Energy System Development"];

function Heading({ eyebrow, children }: { eyebrow: string; children: React.ReactNode }) {
  return <div className="mb-10 max-w-3xl sm:mb-12"><p className="text-xs font-bold uppercase tracking-[0.2em] text-aica-700">{eyebrow}</p><h2 className="mt-4 text-3xl font-semibold tracking-tight text-slate-950 sm:text-4xl">{children}</h2></div>;
}

export default function Page() {
  return <main id="main-content">
    <section id="overview" className="relative overflow-hidden border-b border-slate-200 bg-white py-20 sm:py-24 lg:py-28">
      <div aria-hidden="true" className="absolute inset-y-0 right-0 hidden w-[42%] opacity-60 lg:block" style={{ backgroundImage: "linear-gradient(to right,transparent,rgba(242,248,242,.72)),linear-gradient(rgba(36,91,61,.07) 1px,transparent 1px),linear-gradient(90deg,rgba(36,91,61,.07) 1px,transparent 1px)", backgroundSize: "100% 100%,48px 48px,48px 48px" }} />
      <Container className="relative"><div className="max-w-4xl"><p className="text-xs font-bold uppercase tracking-[0.22em] text-aica-700">Documentation</p><h1 className="mt-5 text-4xl font-semibold tracking-tight text-slate-950 sm:text-5xl lg:text-6xl">The engineering record of the AICA programme.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-700">AICA documentation records the assumptions, architecture decisions, research questions, development methods, and validation activities that shape the programme.</p><p className="mt-4 max-w-3xl text-base leading-7 text-slate-600">Documents evolve as engineering evidence matures. Conceptual material, simulation results, subsystem validation, and future prototype testing should remain clearly distinguishable.</p><div className="mt-9 inline-flex items-center gap-3 border border-slate-200 bg-aica-25 px-4 py-3"><span className="h-2 w-2 rounded-full bg-aica-600" aria-hidden="true" /><div><p className="text-[.65rem] font-bold uppercase tracking-[.18em] text-slate-500">Documentation status</p><p className="mt-0.5 text-sm font-semibold text-slate-900">Active <span className="px-1 text-slate-300">·</span> Continuously evolving</p></div></div></div></Container>
    </section>
    <nav aria-label="Documentation sections" className="border-b border-slate-200 bg-aica-25/80 py-4"><Container><div className="flex flex-wrap gap-x-6 gap-y-2">{nav.map(([label, href]) => <a key={href} href={href} className="text-sm font-medium text-slate-600 hover:text-aica-700">{label}</a>)}</div></Container></nav>

    <section id="library" className="scroll-mt-24 bg-white py-20 sm:py-24"><Container><Heading eyebrow="Document library">Navigate the programme documentation.</Heading><div className="grid gap-px overflow-hidden border border-slate-200 bg-slate-200 md:grid-cols-2 lg:grid-cols-3">{library.map(([category, title, description, href, status]) => { const body = <><p className="text-[.68rem] font-bold uppercase tracking-[.18em] text-aica-700">{category}</p><h3 className="mt-4 text-xl font-semibold text-slate-950">{title}</h3><p className="mt-3 flex-1 text-sm leading-6 text-slate-600">{description}</p>{href ? <span className="mt-7 text-sm font-semibold text-aica-700">Open documentation →</span> : <span className="mt-7 w-fit border border-slate-200 bg-slate-50 px-2.5 py-1 text-xs font-semibold text-slate-500">{status}</span>}</>; return href ? <Link key={title} href={href} className="flex min-h-64 flex-col bg-white p-6 transition-colors hover:bg-aica-25 sm:p-7">{body}</Link> : <article key={title} className="flex min-h-64 flex-col bg-white p-6 sm:p-7">{body}</article>; })}</div></Container></section>

    <section id="structure" className="scroll-mt-24 border-y border-slate-200 bg-aica-25 py-20 sm:py-24"><Container><Heading eyebrow="Document structure">Different documents carry different levels of engineering authority.</Heading><div className="grid gap-5 lg:grid-cols-2">{documentClasses.map((item) => <article key={item.n} className="border border-slate-200 bg-white p-6 sm:p-8"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-xs font-bold uppercase tracking-[.2em] text-aica-700">Class {item.n}</p>{item.future && <span className="border border-aica-200 bg-aica-50 px-2.5 py-1 text-xs font-bold uppercase tracking-wider text-aica-800">Future programme stage</span>}</div><h3 className="mt-5 text-2xl font-semibold uppercase tracking-tight text-slate-950">{item.title}</h3><p className="mt-4 text-sm leading-6 text-slate-600">{item.purpose}</p><div className="mt-6 border-l-2 border-aica-500 pl-4"><p className="text-[.65rem] font-bold uppercase tracking-[.18em] text-slate-500">Status meaning</p><p className="mt-1 text-sm font-semibold text-slate-900">{item.status}</p></div><ul className="mt-6 grid gap-2 border-t border-slate-200 pt-5 text-sm text-slate-600 sm:grid-cols-2">{item.examples.map((example) => <li key={example} className="flex gap-2"><span className="text-aica-600">—</span>{example}</li>)}</ul></article>)}</div></Container></section>

    <section id="evidence" className="scroll-mt-24 bg-white py-20 sm:py-24"><Container><Heading eyebrow="Evidence status">Read every claim in the context of its evidence.</Heading><div className="border-y border-slate-200">{evidence.map(([label, meaning], index) => <div key={label} className="grid gap-2 border-b border-slate-200 py-5 last:border-b-0 sm:grid-cols-[3rem_13rem_1fr] sm:items-baseline"><span className="hidden font-mono text-xs text-slate-400 sm:block">0{index + 1}</span><h3 className="text-sm font-bold uppercase tracking-[.12em] text-slate-950">{label}</h3><p className="text-sm leading-6 text-slate-600">{meaning}</p></div>)}</div><p className="mt-8 border-l-2 border-aica-500 bg-aica-25 px-5 py-4 text-sm leading-6 text-slate-700"><strong className="text-slate-950">Important:</strong> A document&apos;s status indicates the maturity of its supporting evidence, not the importance of the work.</p><p className="mt-4 border border-slate-300 bg-slate-50 px-5 py-4 text-sm font-semibold leading-6 text-slate-900">Performance targets must not be presented as measured vehicle capabilities before appropriate physical validation.</p></Container></section>

    <section id="principles" className="scroll-mt-24 border-y border-slate-200 bg-aica-25 py-20 sm:py-24"><Container><Heading eyebrow="Documentation principles">Documentation is part of the engineering process.</Heading><div className="grid gap-x-10 gap-y-8 sm:grid-cols-2 lg:grid-cols-4">{principles.map(([title, description], index) => <article key={title} className="border-t border-slate-300 pt-5"><p className="font-mono text-xs text-aica-700">0{index + 1}</p><h3 className="mt-3 text-sm font-bold uppercase tracking-[.12em] text-slate-950">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{description}</p></article>)}</div></Container></section>

    <section id="history" className="scroll-mt-24 bg-white py-20 sm:py-24"><Container><Heading eyebrow="Programme history">A long-term engineering programme.</Heading><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-aica-700">Concept &amp; Research</p><p className="mt-3 text-3xl font-semibold tracking-tight text-slate-950">2014 <span className="text-slate-300">—</span> Present</p><p className="mt-5 max-w-xl text-base leading-7 text-slate-600">The AICA concept and underlying engineering research began in 2014. The programme has developed through long-term conceptual work, architecture exploration, calculations, system studies, and progressively more structured engineering documentation.</p></div><ol className="border-l border-slate-300 pl-6">{[["2014", "Concept & Research begins"], ["Present", "Structured engineering programme, simulation, system architecture, documentation, and preparation for progressive validation"], ["Future", "Subsystem testing · integration · demonstrator · physical vehicle validation"]].map(([time, text]) => <li key={time} className="relative border-b border-slate-200 py-5 first:pt-0 last:border-b-0 last:pb-0"><span aria-hidden="true" className="absolute -left-[1.68rem] top-6 h-2.5 w-2.5 rounded-full border-2 border-white bg-aica-600" /><p className="text-xs font-bold uppercase tracking-[.18em] text-aica-700">{time}</p><p className="mt-2 text-sm leading-6 text-slate-700">{text}</p></li>)}</ol></div></Container></section>

    <section id="records" className="scroll-mt-24 border-y border-slate-200 bg-aica-25 py-20 sm:py-24"><Container><Heading eyebrow="Engineering records">Recent programme documentation.</Heading><div className="grid gap-px overflow-hidden border border-slate-200 bg-slate-200 md:grid-cols-3">{records.map((title, index) => <Link key={title} href="/journal" className="group bg-white p-6 transition-colors hover:bg-aica-25"><p className="font-mono text-xs text-slate-400">Record 0{index + 1}</p><h3 className="mt-5 text-lg font-semibold text-slate-950">{title}</h3><p className="mt-6 text-sm font-semibold text-aica-700">View in Engineering Journal →</p></Link>)}</div><p className="mt-5 text-sm leading-6 text-slate-500">These records form part of the living engineering journal. Individual record pages are not currently published.</p></Container></section>

    <section className="bg-white py-20 sm:py-24"><Container><div className="border-l-2 border-aica-600 pl-6 sm:pl-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-aica-700">Continue exploring</p><h2 className="mt-4 text-3xl font-semibold tracking-tight text-slate-950 sm:text-4xl">Explore the engineering programme.</h2><p className="mt-5 max-w-3xl text-base leading-7 text-slate-600">Research defines the questions. Documentation records the reasoning. Validation determines what the platform can ultimately achieve.</p><div className="mt-8 flex flex-wrap items-center gap-3"><Button href="/research">Explore Research</Button><Button href="/journal" variant="secondary">Read Engineering Journal</Button><Link href="/roadmap" className="px-3 py-2 text-sm font-semibold text-aica-700 hover:text-aica-900">Development Roadmap →</Link></div></div></Container></section>
  </main>;
}
