import Link from "next/link";
import { Button } from "@/components/Button";
import { Container } from "@/components/Container";
import { createPageMetadata } from "@/lib/metadata";

const description = "Investor information for AICA, an early-stage engineering programme developing an unconventional advanced air mobility platform through progressive analysis, simulation, and physical validation.";
export const metadata = createPageMetadata({ title: "AICA Investor Information | Engineering the Next Stage", description, path: "/investors", absoluteTitle: true });

const story = [
  ["A Different Question About Flight", ["AICA begins with a different question about advanced air mobility: can a vehicle be engineered around an unconventional architecture rather than simply reproducing an aeroplane, helicopter, or rotorcraft?", "The concept is intended to operate without exposed propellers or external rotors. That direction is an engineering hypothesis to be investigated, not evidence of a completed aircraft."]],
  ["Where the Idea Began", ["My interest in unconventional flight began long before AICA became an engineering project.", "As a teenager, I was fascinated by science fiction, popular science publications, and the intense public interest in unidentified flying objects that surrounded the subject during the 1990s.", "What interested me most was not the mythology around UFOs itself, but the broader question it suggested: could a flying vehicle operate according to principles fundamentally different from the aircraft we already know?", "That question stayed with me.", "I began imagining a vehicle that would not simply reproduce the familiar architecture of an aeroplane, helicopter, or rotorcraft. I was particularly interested in the possibility of creating a vehicle capable of flight without exposed propellers and without relying on the conventional rotor-based approach to generating lift.", "At that stage, it was only an idea—curiosity shaped by science fiction and an interest in technology.", "Later, I studied engineering.", "That changed the way I approached the question. What had begun as imagination gradually became an engineering problem: if such a vehicle were to exist, what physical principles could make it possible? What architecture would it require? How would energy, control, structure, safety, and propulsion have to interact?", "The original idea never disappeared.", "Over time, it developed from a thought experiment into calculations, concepts, system studies, and eventually a structured engineering programme.", "That programme became AICA.", "The project therefore did not begin with a business plan or an attempt to follow the emerging air-mobility market. It grew from a long-standing technical curiosity: the desire to investigate whether a different approach to flight could be engineered in practice.", "Today, that same question remains at the centre of AICA.", "The difference is that it is no longer approached only through imagination.", "It is approached through engineering."]],
  ["From Idea to Engineering Programme", ["Concept and research work began in 2014. Since then, the original question has been organised into a long-term programme of documented concepts, calculations, architecture studies, and simulation-led investigation.", "The programme remains early-stage. Its present value lies in the engineering work assembled so far and in a disciplined route toward stronger evidence."]],
  ["The AICA Approach", ["AICA investigates an unconventional air-mobility architecture in which propulsion, energy, control, software, structure, and safety must be considered as an integrated system.", "The work is currently supported primarily by conceptual, analytical, and simulated evidence. Subsystem development and controlled physical testing are the necessary next steps."]],
  ["Protecting the Core Technology", ["The central propulsion concept is proprietary. Public materials intentionally describe the system architecture and development logic without exposing confidential implementation details.", "Appropriate technical due diligence may be conducted during serious investment discussions under suitable confidentiality arrangements."]],
  ["Engineering Before Claims", ["AICA is not presented as a completed aircraft, a physically validated vehicle, a production-ready system, a certified aircraft, or a guaranteed commercial outcome.", "Technical claims must follow evidence. Analysis and simulation can guide design decisions, but they do not replace measured results from hardware."]],
  ["Why Funding Is Needed Now", ["The programme has reached the point where stronger conclusions require physical engineering work: specialised analysis, laboratory capability, representative hardware, instrumentation, bench testing, and progressive integration.", "Investment is sought to transform documented engineering concepts into measurable engineering evidence."]],
  ["Capital as Engineering Risk Reduction", ["Capital would be applied to resolving technical uncertainty in a controlled sequence. Each stage should test critical assumptions, expose weaknesses, and inform whether the programme is ready to proceed.", "This is not manufactured certainty. It is a process for replacing assumptions with measurements and reducing risk through engineering evidence."]],
  ["What Investment Should Unlock", ["Investment should unlock deeper modelling, laboratory infrastructure, subsystem hardware, controlled bench validation, and—only when earlier results justify it—integrated experimental systems.", "Progress would be milestone-led, with later work conditional on the technical outcomes of earlier work."]],
  ["Why AICA", ["AICA is a long-horizon independent engineering programme built around an original technical question, sustained research since 2014, and a commitment to evidence before performance claims.", "Its case for support is the opportunity to investigate a distinct architecture through disciplined engineering—not a claim that the central uncertainties have already been solved."]],
  ["The Opportunity and the Risk", ["If the architecture proves technically viable, it may contribute a different approach to advanced air mobility. The opportunity is meaningful precisely because the engineering question is difficult and unresolved.", "Technical, financial, regulatory, manufacturing, and execution risks remain substantial. There can be no assurance that every assumption or programme stage will succeed."]],
  ["What Success Would Mean", ["Near-term success means producing credible physical evidence: tested subsystems, repeatable measurements, documented results, and informed decisions about integration.", "Longer-term vehicle development would become appropriate only if progressive validation supports it."]],
  ["The Next Chapter", ["The next chapter is a transition from analytical and simulated engineering toward subsystem development, bench testing, and progressive physical validation.", "AICA is seeking aligned investors and engineering partners who understand that deep-technology progress is earned stage by stage."]],
] as const;
const development = [["Engineering Analysis", "Current evidence"], ["Simulation", "Current evidence"], ["Subsystem Development", "Future stage"], ["Bench Validation", "Future stage"], ["System Integration", "Future stage"], ["Experimental Demonstrator", "Future stage"], ["Vehicle-Level Validation", "Future stage"]] as const;
const capital = [["Engineering & Simulation", "Specialised modelling, calculations, numerical analysis, and design refinement."], ["Laboratory Infrastructure", "Instrumentation, measurement systems, test equipment, power systems, and safety infrastructure."], ["Subsystem Development", "Fabrication and acquisition of hardware required to test critical engineering assumptions."], ["Bench Testing", "Controlled experiments and physical subsystem validation."], ["System Integration", "Progressive integration of sufficiently mature subsystems."], ["Experimental Demonstrator", "Development of representative experimental hardware after prior engineering milestones are achieved."]] as const;
const funding = ["Engineering Validation", "Subsystem Validation", "Integrated Demonstrator", "Vehicle Development", "Industrialisation"] as const;

function Heading({ eyebrow, title, copy }: { eyebrow: string; title: string; copy?: string }) { return <div className="mb-10 max-w-3xl sm:mb-12"><p className="text-xs font-bold uppercase tracking-[0.2em] text-aica-700">{eyebrow}</p><h2 className="mt-4 text-3xl font-semibold tracking-tight text-slate-950 sm:text-4xl">{title}</h2>{copy && <p className="mt-5 text-base leading-7 text-slate-600 sm:text-lg">{copy}</p>}</div>; }

export default function InvestorsPage() { return <main id="main-content" tabIndex={-1}>
  <section className="relative overflow-hidden border-b border-slate-200 bg-white py-20 sm:py-24 lg:py-28"><div aria-hidden="true" className="absolute inset-y-0 right-0 hidden w-2/5 opacity-60 lg:block" style={{ backgroundImage: "linear-gradient(to right,transparent,rgba(242,248,242,.85)),linear-gradient(rgba(36,91,61,.07) 1px,transparent 1px),linear-gradient(90deg,rgba(36,91,61,.07) 1px,transparent 1px)", backgroundSize: "100% 100%,48px 48px,48px 48px" }} /><Container className="relative"><div className="max-w-4xl"><p className="text-xs font-bold uppercase tracking-[0.22em] text-aica-700">Investor Information</p><h1 className="mt-5 text-4xl font-semibold tracking-tight text-slate-950 sm:text-5xl lg:text-6xl">From engineering concept to physical evidence.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-700">AICA is an early-stage independent engineering programme investigating a new approach to advanced air mobility.</p><p className="mt-4 max-w-3xl text-base leading-7 text-slate-600">The programme is seeking the resources required to move from analytical and simulated engineering toward subsystem development, bench testing, and progressive physical validation.</p><dl className="mt-9 flex flex-col gap-3 sm:flex-row"><div className="border border-slate-200 bg-aica-25 px-4 py-3"><dt className="text-[.65rem] font-bold uppercase tracking-[.18em] text-slate-500">Programme origin</dt><dd className="mt-1 text-sm font-semibold text-slate-950">2014</dd></div><div className="border border-slate-200 bg-aica-25 px-4 py-3"><dt className="text-[.65rem] font-bold uppercase tracking-[.18em] text-slate-500">Current evidence</dt><dd className="mt-1 text-sm font-semibold text-slate-950">Concept · Analytical · Simulated</dd></div></dl></div></Container></section>
  <section className="border-b border-slate-200 bg-aica-25 py-14 sm:py-16"><Container><p className="max-w-4xl border-l-2 border-aica-600 pl-6 text-xl font-semibold leading-8 text-slate-950 sm:pl-8 sm:text-2xl">Investment is sought to transform documented engineering concepts into measurable engineering evidence.</p></Container></section>
  <section className="bg-white py-20 sm:py-24"><Container><Heading eyebrow="Investment story" title="A long-standing technical question, developed through engineering." /><div className="mx-auto max-w-3xl">{story.map(([heading, paragraphs], i) => <article key={heading} className="border-t border-slate-200 py-9 first:border-t-0 first:pt-0"><div className="grid gap-3 sm:grid-cols-[3rem_1fr]"><p className="font-mono text-xs text-aica-700">{String(i + 1).padStart(2, "0")}</p><div><h3 className="text-xl font-semibold tracking-tight text-slate-950 sm:text-2xl">{heading}</h3><div className="mt-4 space-y-4">{paragraphs.map(p => <p key={p} className="text-base leading-8 text-slate-600">{p}</p>)}</div></div></div></article>)}</div></Container></section>
  <section className="border-y border-slate-200 bg-aica-25 py-20 sm:py-24"><Container><Heading eyebrow="Development logic" title="Evidence advances in stages." copy="Current analytical and simulated work informs the programme. All subsequent stages are future work and depend on successful prior outcomes." /><ol className="grid gap-px overflow-hidden border border-slate-200 bg-slate-200 sm:grid-cols-2 lg:grid-cols-7">{development.map(([name, status], i) => <li key={name} className="bg-white p-5"><p className="font-mono text-xs text-aica-700">{String(i + 1).padStart(2, "0")}</p><h3 className="mt-5 text-sm font-semibold leading-5 text-slate-950">{name}</h3><p className={`mt-4 text-[.65rem] font-bold uppercase tracking-[.13em] ${i < 2 ? "text-aica-700" : "text-slate-500"}`}>{status}</p></li>)}</ol></Container></section>
  <section className="bg-white py-20 sm:py-24"><Container><Heading eyebrow="Use of capital" title="Funding engineering progress, not manufactured certainty." /><div className="grid gap-px overflow-hidden border border-slate-200 bg-slate-200 sm:grid-cols-2 lg:grid-cols-3">{capital.map(([title, text], i) => <article key={title} className="bg-white p-6 sm:p-7"><p className="font-mono text-xs text-aica-700">{String(i + 1).padStart(2, "0")}</p><h3 className="mt-4 text-lg font-semibold text-slate-950">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></Container></section>
  <section className="border-y border-slate-200 bg-aica-25 py-20 sm:py-24"><Container><Heading eyebrow="Funding stages" title="Capital aligned to technical maturity." copy="Later stages depend on successful technical outcomes from earlier stages. No later stage is presented as complete or assured." /><ol className="grid gap-4 md:grid-cols-5">{funding.map((name, i) => <li key={name} className="border-t-2 border-aica-600 bg-white p-5"><p className="text-[.65rem] font-bold uppercase tracking-[.15em] text-slate-500">Funding Stage {i + 1}</p><h3 className="mt-3 text-base font-semibold text-slate-950">{name}</h3><p className="mt-5 font-mono text-xs text-slate-400">0{i + 1}</p></li>)}</ol></Container></section>
  <section className="bg-white py-20 sm:py-24"><Container><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr] lg:gap-16"><Heading eyebrow="Technology confidentiality" title="Architecture in public. Implementation protected." /><div className="space-y-5 border-t border-slate-300 pt-6 text-base leading-8 text-slate-600"><p>The central propulsion concept is proprietary.</p><p>Public materials intentionally describe system architecture without exposing confidential implementation details.</p><p>Appropriate technical due diligence may be conducted during serious investment discussions under suitable confidentiality arrangements.</p></div></div></Container></section>
  <section className="border-y border-amber-200 bg-amber-50/60 py-14 sm:py-16" aria-labelledby="risk-heading"><Container><div className="max-w-4xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-amber-800">Early-stage technology risk</p><h2 id="risk-heading" className="sr-only">Early-stage technology risk disclosure</h2><div className="mt-5 space-y-3 text-base leading-7 text-slate-700"><p>AICA is an early-stage deep-technology programme. There is currently no completed AICA vehicle whose final performance can be demonstrated.</p><p>Technical, financial, regulatory, manufacturing, and execution risks remain substantial.</p><p>Engineering assumptions may change as simulation and physical testing produce stronger evidence.</p><p>Future programme stages depend on successful validation, available resources, and engineering outcomes.</p></div></div></Container></section>
  <section className="bg-white py-20 sm:py-24"><Container><Heading eyebrow="Investor materials" title="Materials for programme review." /><div className="grid gap-px overflow-hidden border border-slate-200 bg-slate-200 md:grid-cols-3"><article className="bg-white p-6"><h3 className="text-lg font-semibold text-slate-950">Investor Deck</h3><p className="mt-6 text-xs font-bold uppercase tracking-[.15em] text-slate-500">Status: In preparation</p></article><article className="bg-white p-6"><h3 className="text-lg font-semibold text-slate-950">Executive Summary</h3><p className="mt-6 text-xs font-bold uppercase tracking-[.15em] text-slate-500">Status: In preparation</p></article><Link href="/whitepaper" className="group bg-white p-6 transition-colors hover:bg-aica-25"><h3 className="text-lg font-semibold text-slate-950">Engineering Overview</h3><p className="mt-6 text-xs font-bold uppercase tracking-[.15em] text-aica-700">Status: Available</p><p className="mt-5 text-sm font-semibold text-aica-700">View overview →</p></Link></div></Container></section>
  <section className="border-t border-slate-200 bg-aica-25 py-20 sm:py-24"><Container><div className="max-w-4xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-aica-700">Next stage</p><h2 className="mt-4 text-3xl font-semibold tracking-tight text-slate-950 sm:text-4xl">Interested in the next stage of AICA?</h2><p className="mt-5 max-w-3xl text-base leading-7 text-slate-600 sm:text-lg">AICA welcomes conversations with investors, engineering partners, and organisations interested in supporting progressive technical validation.</p><div className="mt-8 flex flex-col items-start gap-3 sm:flex-row sm:items-center"><span aria-disabled="true" className="inline-flex min-h-11 cursor-not-allowed items-center justify-center rounded-full border border-slate-200 bg-slate-100 px-4 text-sm font-semibold text-slate-500">Investor contact channel — being prepared</span><Button href="/whitepaper" variant="secondary">Engineering Overview</Button></div></div></Container></section>
</main>; }
