import { Container } from "@/components/Container";
import { SupportCard } from "@/components/SupportCard";
import { createPageMetadata } from "@/lib/metadata";

const description = "Support the continued engineering development of AICA through voluntary cryptocurrency contributions.";
export const metadata = createPageMetadata({ title: "Support AICA | Engineering Development", description, path: "/support", absoluteTitle: true });

const supportOptions = [
  { asset: "USDC", network: "Ethereum (ERC-20)", address: "0xe5e00Baf7fa88d00628fC6886A79E4Ddd0FE0258" },
  { asset: "USDT", network: "TRON (TRC-20)", address: "TJJEoMgBdMwooMMHewQxdaoysvffFjSU79" },
  { asset: "ETH", network: "Ethereum", address: "0xe5e00Baf7fa88d00628fC6886A79E4Ddd0FE0258" },
  { asset: "SOL", network: "Solana", address: "ENjb9Qgkd2VL6ipxGmDqdXytoVkut3yopcnpfCy4NYdQ" },
] as const;

export default function SupportPage() {
  return <main id="main-content" tabIndex={-1}>
    <section className="relative overflow-hidden border-b border-slate-200 bg-white py-20 sm:py-24 lg:py-28"><div aria-hidden="true" className="absolute inset-y-0 right-0 hidden w-2/5 opacity-60 lg:block" style={{ backgroundImage: "linear-gradient(to right,transparent,rgba(242,248,242,.85)),linear-gradient(rgba(36,91,61,.07) 1px,transparent 1px),linear-gradient(90deg,rgba(36,91,61,.07) 1px,transparent 1px)", backgroundSize: "100% 100%,48px 48px,48px 48px" }} /><Container className="relative"><div className="max-w-4xl"><p className="text-xs font-bold uppercase tracking-[0.22em] text-aica-700">Support AICA</p><h1 className="mt-5 text-4xl font-semibold tracking-tight text-slate-950 sm:text-5xl lg:text-6xl">Support AICA Development</h1><div className="mt-7 max-w-3xl space-y-4 text-base leading-7 text-slate-600 sm:text-lg sm:leading-8"><p>AICA is an independent engineering initiative exploring advanced approaches to vertical mobility and future aerospace systems.</p><p>Voluntary support helps expand the scope and pace of engineering work, including research, simulation, experimental development, acquisition of components and equipment, and future prototype validation.</p><p>AICA does not publicly disclose proprietary details of its core technology.</p></div></div></Container></section>
    <section className="bg-aica-25 py-20 sm:py-24" aria-labelledby="crypto-support-heading"><Container><div className="mb-10 max-w-3xl sm:mb-12"><p className="text-xs font-bold uppercase tracking-[0.2em] text-aica-700">Voluntary contributions</p><h2 id="crypto-support-heading" className="mt-4 text-3xl font-semibold tracking-tight text-slate-950 sm:text-4xl">Crypto Support</h2><p className="mt-5 text-base leading-7 text-slate-600 sm:text-lg">Cryptocurrency provides a simple way for individuals around the world to support the continued development of AICA.</p></div>
      <aside className="mb-8 border border-amber-200 bg-amber-50/70 p-6 sm:p-7" aria-labelledby="network-warning-heading"><p className="text-xs font-bold uppercase tracking-[0.2em] text-amber-800">Important</p><h3 id="network-warning-heading" className="mt-3 text-xl font-semibold text-slate-950">Always verify both the asset and network before sending.</h3><ul className="mt-5 grid gap-2 text-sm leading-6 text-slate-700 sm:grid-cols-2"><li><strong>USDC</strong> must be sent using <strong>Ethereum (ERC-20)</strong>.</li><li><strong>USDT</strong> must be sent using <strong>TRON (TRC-20)</strong>.</li><li><strong>ETH</strong> must be sent using <strong>Ethereum</strong>.</li><li><strong>SOL</strong> must be sent using <strong>Solana</strong>.</li></ul><div className="mt-5 space-y-2 text-sm leading-6 text-slate-700"><p>Transactions sent using an incompatible network may be permanently lost.</p><p>Send a small test transaction first if you are uncertain.</p></div></aside>
      <div className="grid min-w-0 gap-5 lg:grid-cols-2">{supportOptions.map((option) => <SupportCard key={`${option.asset}-${option.network}`} {...option} />)}</div></Container></section>
    <section className="border-t border-slate-200 bg-white py-20 sm:py-24" aria-labelledby="voluntary-support-heading"><Container><div className="max-w-4xl border-l-2 border-aica-600 pl-6 sm:pl-8"><p className="text-xs font-bold uppercase tracking-[0.2em] text-aica-700">Support notice</p><h2 id="voluntary-support-heading" className="mt-4 text-3xl font-semibold tracking-tight text-slate-950 sm:text-4xl">Voluntary Support</h2><div className="mt-5 space-y-4 text-base leading-7 text-slate-600 sm:text-lg sm:leading-8"><p>Financial support provided through this page is voluntary and is intended to support the continued engineering development of AICA.</p><p>Support through this page does not constitute the purchase of equity, securities, AICA tokens, products, services, or any promise of financial return.</p><p>Private investment discussions, if any, are separate from voluntary support.</p></div></div></Container></section>
  </main>;
}
